### ISSUE TITLE
Taylor remainder convergence test demo on the website did not work

### ISSUE THREAD

**Issue by meiyue1989** [dolfin-adjoint/dolfin-adjoint#5]
Dear all,

I am trying to run the Taylor remainder convergence test shown in the dolfin-adjoint website (http://www.dolfin-adjoint.org/en/latest/documentation/verification.html). The program is named “tutorial4.py“. The error message is shown below:

Traceback (most recent call last):

File "/home/meiyue/research-bk/Fenics_project/optimization/tutorial4.py", line 31, in <module>
    dJdnu = compute_gradient(J, nu)

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/pyadjoint/drivers.py", line 31, in compute_gradient
    grads = [i.get_derivative(options=options) for i in m]

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/pyadjoint/drivers.py", line 31, in <listcomp>
    grads = [i.get_derivative(options=options) for i in m]

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/fenics_adjoint/types/constant.py", line 42, in get_derivative
    return self._ad_convert_type(self.adj_value, options=options)

AttributeError: 'Constant' object has no attribute 'adj_value'

Thus, I changed this line “dJdnu = compute_gradient(J, nu)” by ”dJdnu = compute_gradient(J, Constant(nu))”. However, even I did this and ran the code for more than 10 mins, I found the code keep running the Newton’s iteration without showing the convengence information. I would like to known how to get it fixed.

‌

All the best,

Yue Mei

**Comment by jorgensd** [comment]
The following code:
```python
from fenics import *
from fenics_adjoint import *

n = 30
mesh = UnitSquareMesh(n, n)
V = VectorFunctionSpace(mesh, "CG", 2)

u = project(Expression(("sin(2*pi*x[0])", "cos(2*pi*x[1])"), degree=2),  V)

u_next = Function(V)
v = TestFunction(V)

nu = Constant(0.0001)

timestep = Constant(0.01)

F = (inner((u_next - u)/timestep, v)
     + inner(grad(u_next)*u_next, v)
     + nu*inner(grad(u_next), grad(v)))*dx

bc = DirichletBC(V, (0.0, 0.0), "on_boundary")

t = 0.0
end = 0.1
while (t <= end):
    solve(F == 0, u_next, bc)
    u.assign(u_next)
    t += float(timestep)

J = assemble(inner(u, u)*dx)
nu_c = Control(nu)
dJdnu = compute_gradient(J, nu_c)

h = Constant(0.0001)  # the direction of the perturbation
# the functional as a pure function of nu
Jhat = ReducedFunctional(J, nu_c)
conv_rate = taylor_test(Jhat, nu, h)
``` 
runs with 
```bash
docker run -ti --network=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/root/shared -w /root/shared --rm  ghcr.io/dolfin-adjoint/dolfin-adjoint:v2023.0.0.post0
```
I've made a PR with a fix for the online tutorial
